### ISSUE TITLE
Icon is blurry at 110% scaling (DPI 106)

### ISSUE THREAD

**Issue by 28andrew** [File-New-Project/EarTrumpet#495]
I recently switched from a 1680x1050 to a 2560x1080 monitor. The EarTrumpet tray icon now looks like this:
![image](https://user-images.githubusercontent.com/9660418/80395222-81999300-8878-11ea-9e77-7763bca9635e.png)

I don't recall it looking like that? Is this an issue with my resolution?

**Comment by 28andrew** [comment]
The legacy icon appears to work just fine:
![image](https://user-images.githubusercontent.com/9660418/80395452-d63d0e00-8878-11ea-87c6-de842f999636.png)

**Comment by riverar** [comment]
Hey @28andrew, thanks for the heads up. We might be missing an icon step. Navigate to Settings > General > About and click Collect troubleshooting data. Copy and paste the top portion of the log (before the ---) into this issue.

**Comment by 28andrew** [comment]
```yml
version: 2.1.7.0
runtimeMinutes: 8119
gdiObjects: 79
userObjects: 44
globalGdiObjects: 3975
globalUserObjects: 3975
handleCount: 990
releaseStage: production
osVersionBuild: 18362.1.amd64fre.19h1_release.190318-1202
osArchitecture: 64 bit
processorCount: 6 core(s)
IsLightTheme: True
IsSystemLightTheme: False
IsRTL: False
IsTransparencyEnabled: True
UseAccentColor: True
AnimationsEnabled: True
IsHighContrast: False
HasIdentity: True
IsShuttingDown: False
Culture: en-US
CurrentUICulture: en-US
systemDpi: 106
taskbarDpi: 106
addons: 
region: US
```
